import {
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss,
  SiReact,
  SiRedux,
  SiReactquery,
  SiVuedotjs,
  SiNextdotjs,
  SiMui,
  SiStyledcomponents,
  SiTailwindcss,
  SiFramer,
  SiReactrouter,
  SiGit,
  SiGithub,
  SiVite,
  SiWebpack,
  SiVercel,
  SiStorybook,
  SiFigma,
  SiFirebase,
  SiJira,
  SiJest,
  SiTestinglibrary,
  SiNodedotjs,
  SiExpress,
  SiGraphql,
  SiMongodb,
  SiMongoose,
  SiGithubcopilot,
  SiPostman,
} from "react-icons/si"
import type { IconType } from "react-icons"

const iconMap: Record<string, IconType> = {
  JavaScript: SiJavascript,
  "JavaScript (ES6+)": SiJavascript,
  TypeScript: SiTypescript,
  HTML5: SiHtml5,
  CSS3: SiCss,
  React: SiReact,
  "React Hooks": SiReact,
  Redux: SiRedux,
  "React Query": SiReactquery,
  "Vue.js": SiVuedotjs,
  "Next.js": SiNextdotjs,
  "Material-UI": SiMui,
  "Styled Components": SiStyledcomponents,
  "Tailwind CSS": SiTailwindcss,
  "Framer Motion": SiFramer,
  "React Router": SiReactrouter,
  Git: SiGit,
  GitHub: SiGithub,
  Vite: SiVite,
  Webpack: SiWebpack,
  Vercel: SiVercel,
  Storybook: SiStorybook,
  Figma: SiFigma,
  Firebase: SiFirebase,
  JIRA: SiJira,
  Jest: SiJest,
  "React Testing Library": SiTestinglibrary,
  "REST API": SiPostman,
  Node: SiNodedotjs,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  GraphQL: SiGraphql,
  MongoDB: SiMongodb,
  Mongoose: SiMongoose,
  "GitHub Copilot": SiGithubcopilot,
}

export function getSkillIcon(name: string): IconType | null {
  return iconMap[name] ?? null
}
